name: Deploy NGINX Configuration

on:
  push:
    branches:
      - main
    paths:
      - "conf.d/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Create SSH private key file
      run: |
        echo "${{ secrets.REMOTE_SSH_KEY }}" > priv.key
        chmod 600 priv.key

    - name: Test NGINX configuration
      run: |
        ssh -i priv.key -p 20548 ${{ secrets.REMOTE_SSH_USERNAME }}@${{ secrets.REMOTE_SSH_HOST }} 'cat /etc/os-release'

    - name: Clean up private key file
      run: rm priv.key
