name: Deploy NGINX Configuration

on:
  push:
    branches:
      - main
    paths:
      - "conf.d/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Copy .conf files to NGINX server
      run: |
        scp -P ${{ secrets.REMOTE_SSH_PORT }} -o StrictHostKeyChecking=no conf.d/*.conf ${{ secrets.REMOTE_SSH_USERNAME }}@${{ secrets.REMOTE_SSH_HOST }}:/etc/nginx/conf.d/

    - name: Test NGINX configuration
      run: |
        ssh -p ${{ secrets.REMOTE_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SSH_USERNAME }}@${{ secrets.NGINX_SERVER_HOST }} 'nginx -t'

    - name: Reload NGINX
      if: success()
      run: |
        ssh -p ${{ secrets.REMOTE_SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SSH_USERNAME }}@${{ secrets.NGINX_SERVER_HOST }} 'nginx -s reload'
